### ISSUE TITLE
Lack of MSU-1 support, no audio playback or not detected.

### ISSUE THREAD

**Issue by ChoroGalaxiaJr** [SarahH12099/MeSNEmu#4] opened 2019-07-05 00:16 UTC
There is no MSU-1 support, running version 1.4.6.4, trying to run Super Mario World MSU-1 hack, manifest.bml, smw_msu1.msu are all good. and it works on snes9x 1.58 for windows.

game patch (bps file) : https://bin.smwcentral.net/u/26932/smw_msu1%252B.zip , pcms not included

Screenshots of MeSNEmu directory (from iTunes) :

https://cdn.discordapp.com/attachments/589897963090739328/596493129482502194/unknown.png
https://cdn.discordapp.com/attachments/589897963090739328/596493198524940291/unknown.png

Did i not set it up correctly or is it not supported yet?

**Comment by SarahH12099** [comment] 2019-07-08 01:40
MSU1 isn't supported in v1.4.6.4 unfortunately, I have been working on it in v2.0.0.0 but the problem is Snes9x's mac port that runs MSU-1 is absolute trash (https://github.com/snes9xgit/snes9x/issues/527) and I haven't been able to rewrite apu enough to fix it fully yet because of it not working properly on mac to begin with.

**Comment by SarahH12099** [comment] 2019-07-14 17:18
MSU-1 will most likely never be supported due to so many complications for it, so I am closing this issue.

**Closed by SarahH12099** 2019-07-14 17:18 UTC
